title: Nathaniel Schmidt
name: Nathaniel Schmidt
author: Nathaniel Schmidt
email: "schmidty2244@gmail.com"
description: Nathaniel Schmidt Github Pages personal site: software project repositories,  blog and percussionist musical endeavours.

url: "https://njschmidt.id.au"
google_analytics: G-CEDD9NZJKK
github_username: njsch

# SCSS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-remote-theme
  # Specific appearance and order of navigation links
nav:
  - title: Home
    url: "/"
  - about.md
  - orgs.md
  - testimonials.md
  - dev.md
  - percussio.md
  - horner.md
  - 1689lbc.md
  - contact.md

show_excerpts: true

environment: prod

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/