timezone: Australia/Melbourne
lang: en-AU
title: Nathaniel Schmidt
name: Nathaniel Schmidt
Author: Nathaniel Schmidt
email: "schmidty2244@gmail.com"
description: Nathaniel Schmidt Github Pages personal site (software project repositories,  blog and percussion musical endeavours).

url: "http://njschmidt.id.au"
google_analytics:

# SCSS
sass:
  sass_dir: _sass
  style: compressed

show_excerpts: true

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
theme: jekyll-theme-cayman

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-remote-theme

# Specific appearance and order of navigation links
nav:
  - title: Home
    url: "/"
  - title: About
    url: "/about"
  - title: Organisations
    url: "/orgs"
  - title: Testimonials
    url: "/testimonials"
  - title: Software Development (Platforms and Activity)
    url: "/dev"
  - title: Percussio
    url: "/percussio"
  - title: Audio Resources
    url: "/audio"
  - title: Christian Resources
    url: "/christian-resources"
  - title: Contact
    url: "/contact"

environment: prod

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
