timezone: Australia/Melbourne
lang: en-AU
title: Nathaniel Schmidt
tagline: personal site
email: "schmidty2244@gmail.com"
description: Nathaniel Schmidt Github Pages personal site (software project repositories,  blog and percussionist musical endeavours).

url: "https://njschmidt.id.au"
google_analytics:
github_username: njsch

# SCSS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
theme: jekyll-theme-cayman

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-remote-theme

social:
  name: Nathaniel Schmidt
  links:
    - https://www.linkedin.com/in/njsch/
    - https://github.com/njsch
    - http://njschmidt.id.au
    - https://www.youtube.com/@njsch
    - https://www.facebook.com/njsch7
    - https://feeds.feedburner.com/nschmidt/


# Specific appearance and order of navigation links
nav:
  - title: Home
    url: "/"
  - title: About
    url: "/about"
  - title: Organisations
    url: "/orgs"
  - title: Testimonials
    url: "/testimonials"
  - title: Software Development (Platforms and Activity)
    url: "/dev"
  - title: Percussio
    url: "/percussio"
  - title: Professor Grant Horner's Ten-List Bible-reading System
    url: "/horner"
  - title: The 1689/2nd London Baptist Confession of Faith (2LBCF)
    url: "/1689lbc.html"
  - title: Contact
    url: "/contact"
  

show_excerpts: true

environment: prod

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/